# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ntPScBsZOTpUQo4qFsbaZVKevAC740hH
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

def getURL(sNumber):
    return f"https://www.govtrack.us/congress/votes/119-2025/s{sNumber}/export/csv"

urls = [getURL(i) for i in range(100, 231)]

combinedDf = None
for i, url in enumerate(urls):
    df = pd.read_csv(url, skiprows=1)

    df = df[['person', 'vote']]


    vote_col = f'vote_{i}'
    df[vote_col] = df['vote'].map({
        'Yea': 1,
        'Nay': -1,
        'Not Voting': 0,
        'NA': 0,
        '': 0
    }).fillna(0)

    df = df[['person', vote_col]]

    if combinedDf is None:
        combinedDf = df
    else:
        combinedDf = pd.merge(combinedDf, df, on='person', how='outer')

print(combinedDf)

combinedDf = combinedDf.fillna(0)
combinedDf.to_csv('combined_votes.csv', index=False)

from google.colab import files
files.download('combined_votes.csv')

